import type { FixtureAdvancedEvidence } from "./advancedEvidence";
import type {
  MatchContext,
  MatchResultInput,
  MatchScores,
  MissingPlayer,
  OddsMarket,
  RecentFormGame,
  TeamContext,
  TeamStats,
} from "./scoringEngine";

export type TipPick = "home" | "draw" | "away";

export type Entrant = {
  id: string;
  name: string;
};

export type UserTip = {
  fixtureId: string;
  entrantId: string;
  pick: TipPick;
  confidence: number;
};

export type Fixture = {
  id: string;
  competition: string;
  round: string;
  date: string;
  homeTeam: string;
  awayTeam: string;
  homeStats: TeamStats;
  awayStats: TeamStats;
  homeRecentForm: RecentFormGame[];
  awayRecentForm: RecentFormGame[];
  homeMissingPlayers: MissingPlayer[];
  awayMissingPlayers: MissingPlayer[];
  homeContext: TeamContext;
  awayContext: TeamContext;
  matchContext: MatchContext;
  oddsMarket: OddsMarket;
  matchResult: MatchResultInput;
  scores: MatchScores;
  advancedEvidence?: FixtureAdvancedEvidence;
};

export const fixtures: Fixture[] = [
  {
    id: "ars-cov",
    competition: "Example League",
    round: "Round 1",
    date: "Opening weekend",
    homeTeam: "Arsenal",
    awayTeam: "Coventry",
    homeStats: {
      played: 38,
      points: 89,
      wins: 28,
      draws: 5,
      losses: 5,
      goalsFor: 91,
      goalsAgainst: 29,
      homePlayed: 19,
      homePoints: 47,
      homeGoalsFor: 48,
      homeGoalsAgainst: 16,
      awayPlayed: 19,
      awayPoints: 42,
      awayGoalsFor: 43,
      awayGoalsAgainst: 13,
    },
    awayStats: {
      played: 46,
      points: 64,
      wins: 17,
      draws: 13,
      losses: 16,
      goalsFor: 70,
      goalsAgainst: 59,
      homePlayed: 23,
      homePoints: 36,
      homeGoalsFor: 38,
      homeGoalsAgainst: 27,
      awayPlayed: 23,
      awayPoints: 28,
      awayGoalsFor: 32,
      awayGoalsAgainst: 32,
    },
    homeRecentForm: [
      { result: "W", goalsFor: 3, goalsAgainst: 1 },
      { result: "W", goalsFor: 2, goalsAgainst: 0 },
      { result: "D", goalsFor: 1, goalsAgainst: 1 },
      { result: "W", goalsFor: 4, goalsAgainst: 1 },
      { result: "L", goalsFor: 0, goalsAgainst: 1 },
    ],
    awayRecentForm: [
      { result: "L", goalsFor: 1, goalsAgainst: 2 },
      { result: "D", goalsFor: 1, goalsAgainst: 1 },
      { result: "W", goalsFor: 2, goalsAgainst: 1 },
      { result: "L", goalsFor: 0, goalsAgainst: 2 },
      { result: "L", goalsFor: 1, goalsAgainst: 3 },
    ],
    homeMissingPlayers: [
      {
        name: "",
        role: "",
        importance: "backup",
        reason: "injury",
        expectedStarter: false,
      },
      {
        name: "",
        role: "",
        importance: "backup",
        reason: "injury",
        expectedStarter: false,
      },
      {
        name: "",
        role: "",
        importance: "backup",
        reason: "injury",
        expectedStarter: false,
      },
    ],
    awayMissingPlayers: [
      {
        name: "Starting goalkeeper",
        role: "Goalkeeper",
        importance: "critical",
        reason: "injury",
        expectedStarter: true,
      },
      {
        name: "Centre-back",
        role: "Defensive leader",
        importance: "key",
        reason: "suspension",
        expectedStarter: true,
      },
      {
        name: "",
        role: "",
        importance: "backup",
        reason: "injury",
        expectedStarter: false,
      },
    ],
    homeContext: {
      mustWin: true,
      titleRace: true,
      relegationBattle: false,
      chasingFinalsOrEurope: false,
      newManagerBounce: false,
      homecomingOrStatement: true,
      rotationRisk: false,
      alreadyQualifiedOrSafe: false,
      cupOrFixtureDistraction: false,
      travelFatigue: false,
    },
    awayContext: {
      mustWin: false,
      titleRace: false,
      relegationBattle: true,
      chasingFinalsOrEurope: false,
      newManagerBounce: false,
      homecomingOrStatement: false,
      rotationRisk: false,
      alreadyQualifiedOrSafe: false,
      cupOrFixtureDistraction: false,
      travelFatigue: true,
    },
    matchContext: {
      derbyOrRivalry: false,
      openingRound: true,
      knockoutOrElimination: false,
      weatherRisk: false,
      unusualVenue: false,
    },
    oddsMarket: {
      homeWinProbability: 78,
      drawProbability: 15,
      awayWinProbability: 7,
      sourceLabel: "Manual market estimate",
    },
    matchResult: { status: "final", homeGoals: 3, awayGoals: 0 },
    scores: {
      qualityGap: 0,
      homeAdvantage: 2,
      recentFormGap: 0,
      headToHeadEdge: 2,
      injuryRisk: 0,
      motivationEdge: 1,
      otherStatsEdge: 1,
      oddsSupport: 1,
      conflictScore: 0,
    },
  },
  {
    id: "eve-wol",
    competition: "Example League",
    round: "Round 1",
    date: "Saturday",
    homeTeam: "Everton",
    awayTeam: "Wolves",
    homeStats: {
      played: 38,
      points: 48,
      wins: 13,
      draws: 9,
      losses: 16,
      goalsFor: 42,
      goalsAgainst: 51,
      homePlayed: 19,
      homePoints: 28,
      homeGoalsFor: 24,
      homeGoalsAgainst: 22,
      awayPlayed: 19,
      awayPoints: 20,
      awayGoalsFor: 18,
      awayGoalsAgainst: 29,
    },
    awayStats: {
      played: 38,
      points: 45,
      wins: 12,
      draws: 9,
      losses: 17,
      goalsFor: 50,
      goalsAgainst: 65,
      homePlayed: 19,
      homePoints: 27,
      homeGoalsFor: 28,
      homeGoalsAgainst: 30,
      awayPlayed: 19,
      awayPoints: 18,
      awayGoalsFor: 22,
      awayGoalsAgainst: 35,
    },
    homeRecentForm: [
      { result: "W", goalsFor: 2, goalsAgainst: 1 },
      { result: "D", goalsFor: 0, goalsAgainst: 0 },
      { result: "L", goalsFor: 1, goalsAgainst: 2 },
      { result: "W", goalsFor: 1, goalsAgainst: 0 },
      { result: "L", goalsFor: 0, goalsAgainst: 1 },
    ],
    awayRecentForm: [
      { result: "L", goalsFor: 0, goalsAgainst: 2 },
      { result: "L", goalsFor: 1, goalsAgainst: 3 },
      { result: "D", goalsFor: 1, goalsAgainst: 1 },
      { result: "W", goalsFor: 2, goalsAgainst: 0 },
      { result: "L", goalsFor: 1, goalsAgainst: 2 },
    ],
    homeMissingPlayers: [
      {
        name: "Main striker",
        role: "Forward",
        importance: "key",
        reason: "doubtful",
        expectedStarter: true,
      },
      {
        name: "",
        role: "",
        importance: "backup",
        reason: "injury",
        expectedStarter: false,
      },
      {
        name: "",
        role: "",
        importance: "backup",
        reason: "injury",
        expectedStarter: false,
      },
    ],
    awayMissingPlayers: [
      {
        name: "Rotation midfielder",
        role: "Midfield",
        importance: "rotation",
        reason: "injury",
        expectedStarter: false,
      },
      {
        name: "",
        role: "",
        importance: "backup",
        reason: "injury",
        expectedStarter: false,
      },
      {
        name: "",
        role: "",
        importance: "backup",
        reason: "injury",
        expectedStarter: false,
      },
    ],
    homeContext: {
      mustWin: true,
      titleRace: false,
      relegationBattle: true,
      chasingFinalsOrEurope: false,
      newManagerBounce: false,
      homecomingOrStatement: false,
      rotationRisk: false,
      alreadyQualifiedOrSafe: false,
      cupOrFixtureDistraction: false,
      travelFatigue: false,
    },
    awayContext: {
      mustWin: false,
      titleRace: false,
      relegationBattle: false,
      chasingFinalsOrEurope: false,
      newManagerBounce: true,
      homecomingOrStatement: false,
      rotationRisk: false,
      alreadyQualifiedOrSafe: false,
      cupOrFixtureDistraction: false,
      travelFatigue: true,
    },
    matchContext: {
      derbyOrRivalry: false,
      openingRound: false,
      knockoutOrElimination: false,
      weatherRisk: true,
      unusualVenue: false,
    },
    oddsMarket: {
      homeWinProbability: 42,
      drawProbability: 29,
      awayWinProbability: 29,
      sourceLabel: "Manual market estimate",
    },
    matchResult: { status: "final", homeGoals: 1, awayGoals: 1 },
    scores: {
      qualityGap: 0,
      homeAdvantage: 2,
      recentFormGap: 0,
      headToHeadEdge: 0,
      injuryRisk: 1,
      motivationEdge: 0,
      otherStatsEdge: 0,
      oddsSupport: 0,
      conflictScore: 1,
    },
  },
  {
    id: "bri-new",
    competition: "Example League",
    round: "Round 1",
    date: "Sunday",
    homeTeam: "Brighton",
    awayTeam: "Newcastle",
    homeStats: {
      played: 38,
      points: 55,
      wins: 15,
      draws: 10,
      losses: 13,
      goalsFor: 58,
      goalsAgainst: 52,
      homePlayed: 19,
      homePoints: 32,
      homeGoalsFor: 33,
      homeGoalsAgainst: 23,
      awayPlayed: 19,
      awayPoints: 23,
      awayGoalsFor: 25,
      awayGoalsAgainst: 29,
    },
    awayStats: {
      played: 38,
      points: 66,
      wins: 20,
      draws: 6,
      losses: 12,
      goalsFor: 74,
      goalsAgainst: 46,
      homePlayed: 19,
      homePoints: 42,
      homeGoalsFor: 45,
      homeGoalsAgainst: 20,
      awayPlayed: 19,
      awayPoints: 24,
      awayGoalsFor: 29,
      awayGoalsAgainst: 26,
    },
    homeRecentForm: [
      { result: "D", goalsFor: 1, goalsAgainst: 1 },
      { result: "W", goalsFor: 3, goalsAgainst: 2 },
      { result: "L", goalsFor: 0, goalsAgainst: 2 },
      { result: "D", goalsFor: 2, goalsAgainst: 2 },
      { result: "W", goalsFor: 2, goalsAgainst: 1 },
    ],
    awayRecentForm: [
      { result: "W", goalsFor: 4, goalsAgainst: 1 },
      { result: "W", goalsFor: 2, goalsAgainst: 0 },
      { result: "D", goalsFor: 1, goalsAgainst: 1 },
      { result: "L", goalsFor: 1, goalsAgainst: 2 },
      { result: "W", goalsFor: 3, goalsAgainst: 1 },
    ],
    homeMissingPlayers: [
      {
        name: "Full-back",
        role: "Defender",
        importance: "starter",
        reason: "injury",
        expectedStarter: true,
      },
      {
        name: "",
        role: "",
        importance: "backup",
        reason: "injury",
        expectedStarter: false,
      },
      {
        name: "",
        role: "",
        importance: "backup",
        reason: "injury",
        expectedStarter: false,
      },
    ],
    awayMissingPlayers: [
      {
        name: "",
        role: "",
        importance: "backup",
        reason: "injury",
        expectedStarter: false,
      },
      {
        name: "",
        role: "",
        importance: "backup",
        reason: "injury",
        expectedStarter: false,
      },
      {
        name: "",
        role: "",
        importance: "backup",
        reason: "injury",
        expectedStarter: false,
      },
    ],
    homeContext: {
      mustWin: false,
      titleRace: false,
      relegationBattle: false,
      chasingFinalsOrEurope: true,
      newManagerBounce: false,
      homecomingOrStatement: false,
      rotationRisk: true,
      alreadyQualifiedOrSafe: false,
      cupOrFixtureDistraction: true,
      travelFatigue: false,
    },
    awayContext: {
      mustWin: true,
      titleRace: false,
      relegationBattle: false,
      chasingFinalsOrEurope: true,
      newManagerBounce: false,
      homecomingOrStatement: false,
      rotationRisk: false,
      alreadyQualifiedOrSafe: false,
      cupOrFixtureDistraction: false,
      travelFatigue: false,
    },
    matchContext: {
      derbyOrRivalry: false,
      openingRound: false,
      knockoutOrElimination: false,
      weatherRisk: false,
      unusualVenue: false,
    },
    oddsMarket: {
      homeWinProbability: 31,
      drawProbability: 27,
      awayWinProbability: 42,
      sourceLabel: "Manual market estimate",
    },
    matchResult: { status: "pending", homeGoals: 0, awayGoals: 0 },
    scores: {
      qualityGap: 0,
      homeAdvantage: 2,
      recentFormGap: 0,
      headToHeadEdge: 0,
      injuryRisk: 0,
      motivationEdge: 0,
      otherStatsEdge: 0,
      oddsSupport: -1,
      conflictScore: 2,
    },
  },
];


export const entrants: Entrant[] = [
  { id: "mitchel", name: "Mitchel" },
  { id: "james", name: "James" },
  { id: "sam", name: "Sam" },
];

export const userTips: UserTip[] = [
  { fixtureId: "ars-cov", entrantId: "mitchel", pick: "home", confidence: 85 },
  { fixtureId: "ars-cov", entrantId: "james", pick: "home", confidence: 78 },
  { fixtureId: "ars-cov", entrantId: "sam", pick: "draw", confidence: 35 },
  { fixtureId: "eve-wol", entrantId: "mitchel", pick: "home", confidence: 55 },
  { fixtureId: "eve-wol", entrantId: "james", pick: "draw", confidence: 50 },
  { fixtureId: "eve-wol", entrantId: "sam", pick: "away", confidence: 52 },
  { fixtureId: "bre-ful", entrantId: "mitchel", pick: "draw", confidence: 48 },
  { fixtureId: "bre-ful", entrantId: "james", pick: "home", confidence: 51 },
  { fixtureId: "bre-ful", entrantId: "sam", pick: "draw", confidence: 60 },
];
